name: testing osx builds

on:
  push:
    branches:
      - test-osx

jobs:
  macos:
    name: MacOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-apple-ios
          - x86_64-apple-ios
        toolchain:
          - stable
        has_native_tls: [true]
        use_cross: [false]

    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          override: true

      - name: Build all features
        uses: actions-rs/cargo@v1
        if: ${{ matrix.has_native_tls }}
        with:
          use-cross: ${{ matrix.use_cross }}
          command: build
          args: --verbose --target ${{ matrix.target }} --all-features

      - name: Test all features
        uses: actions-rs/cargo@v1
        if: ${{ matrix.has_native_tls }}
        with:
          use-cross: ${{ matrix.use_cross }}
          command: test
          args: --verbose --target ${{ matrix.target }} --all-features

      - name: Build no default features
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use_cross }}
          command: build
          args: --verbose --target ${{ matrix.target }} --no-default-features

      - name: Test no default features
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use_cross }}
          command: test
          args: --verbose --target ${{ matrix.target }} --no-default-features

      - name: Build async only
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use_cross }}
          command: build
          args: --verbose --target ${{ matrix.target }} --no-default-features --features async

      - name: Test async only
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use_cross }}
          command: test
          args: --verbose --target ${{ matrix.target }} --no-default-features --features async

      - name: Build rustls
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use_cross }}
          command: build
          args: --verbose --target ${{ matrix.target }} --no-default-features --features tokio_rustls

      - name: Test rustls
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use_cross }}
          command: test
          args: --verbose --target ${{ matrix.target }} --no-default-features --features tokio_rustls

      - name: Build native_tls
        uses: actions-rs/cargo@v1
        if: ${{ matrix.has_native_tls }}
        with:
          use-cross: ${{ matrix.use_cross }}
          command: build
          args: --verbose --target ${{ matrix.target }} --no-default-features --features tokio_native_tls

      - name: Test native_tls
        uses: actions-rs/cargo@v1
        if: ${{ matrix.has_native_tls }}
        with:
          use-cross: ${{ matrix.use_cross }}
          command: test
          args: --verbose --target ${{ matrix.target }} --no-default-features --features tokio_native_tls
