[package]
name = "trovochat"
version = "0.6.6"
authors = ["museun <museun@aleph0cap.com>"]
repository = "https://github.com/museun/trovochat"
edition = "2018"
readme = "README.md"
description = "interface to the irc-side of trovo's chat system"
keywords = [ "trovo", "irc" ]
license = "0BSD"

[badges]
circle-ci = { repository = "museun/trovochat", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[dependencies]
log = "0.4.7"
crossbeam-channel = "0.3.8"
parking_lot = "0.9.0"

[dependencies.serde]
version = "1.0.97"
features = ["derive"]
optional = true

[features]
default = ["serde" ]

[dev-dependencies]
rand = "0.7.0"
serde_json = "1.0.40"
