[package]
name = "trovochat"
version = "0.1.9"
authors = ["museun <museun@aleph0cap.com>"]
repository = "https://github.com/museun/trovochat"
edition = "2018"
description = "interface to the irc-side of trovo's chat system"
keywords = [ "trovo", "irc" ]
license = "0BSD"

[badges]
circle-ci = { repository = "https://github.com/museun/trovochat", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
log = "0.4.6"
parking_lot = "0.7.1"

# trovo doesn't technially use uuid-v4, but something that resembles it 
[dependencies.uuid]
version = "0.7.2"
features = ["v4"]

[dependencies.hashbrown]
version = "0.1.8"
optional = true

[dependencies.serde]
version = "1.0.89"
features = ["derive"]
optional = true

[features]
default = []
serde_hashbrown = ["serde", "hashbrown/serde"]
