[package]
name = "trovochat"
version = "0.1.6"
authors = ["museun <museun@aleph0cap.com>"]
repository = "https://github.com/museun/trovochat"
edition = "2018"
description = "interface to the irc-side of trovo's chat system"
keywords = [ "trovo", "irc" ]
license = "0BSD"

[dependencies]
log = "0.4.6"
parking_lot = "0.7.1"
uuid = { version = "0.7.2", features = ["v4"] }
hashbrown = { version = "0.1.8", features = ["serde"] }
serde = { version = "1.0.89", features = ["derive"], optional = true }

[features]
default = ["teststream", "serde_derive"]
teststream = []
serde_derive = ["serde"]
