[package]
name          = "trovochat"
edition       = "2018"
version       = "0.9.0-beta.0"
authors       = ["museun <museun@aleph0cap.com>"]
keywords      = ["trovo", "irc", "async", "asynchronous", "tokio"]
license       = "MIT OR Apache-2.0"
readme        = "README.md"
description   = "interface to the irc-side of trovo's chat system"
documentation = "https://docs.rs/trovochat/0.8.4/trovochat/"
repository    = "https://github.com/museun/trovochat"
categories    = ["asynchronous", "network-programming", "parser-implementations"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["async", "tokio_native_tls"]
async   = ["tokio", "futures"]

tokio_native_tls = ["tokio-tls", "native-tls"]
tokio_rustls     = ["tokio-rustls", "webpki-roots"]

[dependencies]
log               = { version = "0.4.8" }
static_assertions = { version = "1.1.0" }

# TODO do we need an abort handle now that tokio::Notify exists?
futures    = { version = "0.3.4", optional = true, default-features = false, features = ["alloc"] } # for AbortHandle
# TODO figure out what of these features are actually used
tokio      = { version = "0.2.13", optional = true, features = ["dns", "io-util", "stream", "sync", "tcp", "time"] }

# native tls
tokio-tls  = { version = "0.3.0", optional = true }
native-tls = { version = "0.2.3", optional = true }

# rustls
tokio-rustls  = { version = "0.13.0", optional = true }
webpki-roots  = { version = "0.19.0", optional = true }

serde      = { version = "1.0.104", optional = true, features = ["derive"] }
parking_lot = "0.10.0"


[dev-dependencies]
matches = "0.1.8"
tokio   = { version = "0.2.13", features = ["test-util", "macros"] }
tokio-test = "0.2.0"

[[example]]
name = "demo"
required-features = ["async", "tokio_native_tls"]

[[example]]
name = "short"
required-features = ["async", "tokio_native_tls"]

[[example]]
name = "wait_to_join"
required-features = ["async", "tokio_native_tls"]

[[example]]
name = "wait_to_join"
required-features = ["async", "tokio_native_tls"]

[[example]]
name = "parse"
