[package]
name          = "trovochat"
edition       = "2018"
version       = "0.8.0-beta.4"
authors       = ["museun <museun@aleph0cap.com>"]
keywords      = ["trovo", "irc", "async", "asynchronous", "tokio"]
license       = "MIT OR Apache-2.0"
readme        = "README.md"
description   = "interface to the irc-side of trovo's chat system"
documentation = "https://docs.rs/trovochat/0.8.0-beta.4/trovochat/"
repository    = "https://github.com/museun/trovochat"
categories    = ["asynchronous", "network-programming", "parser-implementations"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["async", "tls"]
async   = ["tokio", "futures"]
tls     = ["tokio-tls", "native-tls"]

[dependencies]
futures    = { version = "0.3", optional = true, default-features = false, features = ["alloc"] } # for AbortHandle
log        = { version = "0.4" }
native-tls = { version = "0.2", optional = true }
serde      = { version = "1",   optional = true, features = ["derive"] }
tokio      = { version = "0.2", optional = true, default-features = false, features = ["dns", "stream", "sync", "tcp", "time"] }
tokio-tls  = { version = "0.3", optional = true }

[dev-dependencies]
matches = "0.1"
tokio   = { version = "0.2", default-features = false, features = ["dns", "io-util", "macros", "stream", "sync", "tcp", "time", "test-util" ] }

[[example]]
name = "demo"
required-features = ["async"]

[[example]]
name = "short"
required-features = ["async"]

[[example]]
name = "parse"
