[package]
name = "trovochat"
version = "0.0.0"
authors = ["museun <museun@aleph0cap.com>"]
edition = "2018"
description = "interface to the irc-side of trovo's chat system"
license = "0BSD"

[dependencies]
log = "0.4.6"
uuid = { version = "0.7.2", features = ["v4"] }
parking_lot = "0.7.1"
hashbrown = { version = "0.1.8", optional = true }
crossbeam-channel = { version = "0.3.8", optional = true }

[features]
default = [ "hashbrown", "teststream" ]
teststream = [ "crossbeam-channel" ]

[dev-dependencies]
serde = {version = "1.0.89", features = ["derive"]}
serde_json = "1.0.39"
