[package]
name          = "trovochat"
edition       = "2018"
version       = "0.10.3"
authors       = ["museun <museun@aleph0cap.com>"]
keywords      = ["trovo", "irc", "async", "asynchronous", "tokio"]
license       = "MIT OR Apache-2.0"
readme        = "README.md"
description   = "interface to the irc-side of trovo's chat system"
documentation = "https://docs.rs/trovochat/latest/trovochat/"
repository    = "https://github.com/museun/trovochat"
categories    = ["asynchronous", "network-programming", "parser-implementations"]

[package.metadata.docs.rs]
features = [ "default", "serde" ]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["async", "tokio_native_tls"]
async   = ["tokio", "futures"]

tokio_native_tls = ["tokio", "futures", "tokio-tls", "native-tls"]
tokio_rustls     = ["tokio", "futures", "tokio-rustls", "webpki-roots"]

[dependencies]
log = "0.4"

futures = { version = "0.3", optional = true, default-features = false } 
# TODO figure out what of these features are actually used
tokio   = { version = "0.2", optional = true, features = ["dns", "io-util", "stream", "sync", "tcp", "time", "macros"] }

# native tls
tokio-tls  = { version = "0.3", optional = true }
native-tls = { version = "0.2", optional = true }

# rustls
tokio-rustls = { version = "0.13", optional = true }
webpki-roots = { version = "0.19", optional = true }

serde = { version = "1.0", optional = true, features = ["derive"] }

# internal stuff
parking_lot       = "0.10"
static_assertions = "1.1"

[dev-dependencies]
matches     = "0.1.8"
tokio       = { version = "0.2.13", features = ["test-util", "macros"] }
tokio-test  = "0.2.0"
doc-comment = "0.3.3"

[[example]]
name = "demo"
required-features = ["async", "tokio_native_tls"]

[[example]]
name = "short"
required-features = ["async", "tokio_native_tls"]

[[example]]
name = "wait_to_join"
required-features = ["async", "tokio_native_tls"]

[[example]]
name = "select"
required-features = ["async", "tokio_native_tls"]

[[example]]
name = "simple_bot"
required-features = ["async", "tokio_native_tls"]

[[example]]
name = "parse"
