[package]
name = "trovochat"
version = "0.0.1"
authors = ["museun <museun@aleph0cap.com>"]
edition = "2018"
description = "interface to the irc-side of trovo's chat system"
license = "0BSD"

[dependencies]
parking_lot = "0.7.1"
uuid = { version = "0.7.2", features = ["v4"] }
hashbrown = { version = "0.1.8", optional = true }

[features]
default = [ "hashbrown", "teststream" ]
teststream = [ ]
