[package]
name          = "trovochat"
edition       = "2018"
version       = "0.11.8"
authors       = ["museun <museun@aleph0cap.com>"]
keywords      = ["trovo", "irc", "async", "asynchronous", "tokio"]
license       = "MIT OR Apache-2.0"
readme        = "README.md"
description   = "interface to the irc-side of trovo's chat system"
documentation = "https://docs.rs/trovochat/latest/trovochat/"
repository    = "https://github.com/museun/trovochat"
categories    = ["asynchronous", "network-programming", "parser-implementations"]

[package.metadata.docs.rs]
features = [ "default", "serde", "crossbeam-channel" ]
rustdoc-args = ["--cfg", "docsrs"]

[features]
# default = ["async", "tokio_native_tls"]
# async   = ["tokio", "futures", "parking_lot"]

# tokio_native_tls = ["tokio", "futures", "tokio-native-tls", "native-tls", "parking_lot"]
# tokio_rustls     = ["tokio", "futures", "tokio-rustls", "webpki-roots", "parking_lot"]

[dependencies]
log = "0.4.11"
serde = { version = "1.0.114", optional = true, features = ["derive"] }

simple_event_map = "0.1.0"

# internal stuff
async-channel    = "1.4.0"
async-mutex      = "1.1.5"
event-listener   = "2.3.0"
futures-lite     = "0.1.10"
parking          = "1.0.6"
pin-project-lite = "0.1.7"

# futures = { version = "0.3.5", optional = true, default-features = false }
# tokio   = { version = "0.2.21", optional = true, features = ["dns", "io-util", "stream", "sync", "tcp", "time", "macros"] }


# native tls
# tokio-native-tls  = { version = "0.1.0", optional = true }
# native-tls        = { version = "0.2.4", optional = true }

# rustls
# tokio-rustls = { version = "0.13.1", optional = true }
# webpki-roots = { version = "0.20.0", optional = true }

# optionally used in the synchronous code
# crossbeam-channel = { version = "0.4.3", optional = true }

[dev-dependencies]
tokio       = { version = "0.2.22", features = ["test-util", "macros"] } # replace this
tokio-test  = "0.2.1"                                                    # replace this
doc-comment = "0.3.3"
serde_json  = "1.0.57"
serde       = { version = "1.0", features = ["derive"] }

# [[example]]
# name = "demo"
# required-features = ["async", "tokio_native_tls"]

# [[example]]
# name = "wait_to_join"
# required-features = ["async", "tokio_native_tls"]

# [[example]]
# name = "simple_bot"
# required-features = ["async", "tokio_native_tls"]

# [[example]]
# name = "retry"
# required-features = ["async", "tokio_native_tls"]

# [[example]]
# name = "parse"
