[package]
name = "trovochat"
version = "0.5.2"
authors = ["museun <museun@aleph0cap.com>"]
repository = "https://github.com/museun/trovochat"
edition = "2018"
readme = "README.md"
description = "interface to the irc-side of trovo's chat system"
keywords = [ "trovo", "irc" ]
license = "0BSD"

[badges]
circle-ci = { repository = "museun/trovochat", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[dependencies]
log = "~0.4"

[dependencies.ratelimit]
version = "0.1"
path = "./crates/ratelimit"

[dependencies.tee]
version = "0.1"
path = "./crates/tee"

[dependencies.parking_lot]
version = "~0.8"
optional = true

[dependencies.hashbrown]
version = "~0.3"
optional = true

[dependencies.serde]
version = "~1.0"
features = ["derive"]
optional = true

[features]
default = [ "all" ]
serde_hashbrown = ["serde", "hashbrown/serde"]
all = ["serde_hashbrown", "parking_lot"]

[dev-dependencies]
rand = "0.6.5"
serde_json = "1.0.39"
