name: Rust

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}    
        
    steps:
    - uses: actions/checkout@v1
   
    - name: Build default features
      run: cargo --verbose
    
    - name: Run tests default features
      run: cargo test --verbose

    - name: Build no features
      run: cargo build --no-default-features --verbose

    - name: Run tests with no features
      run: cargo test --no-default-features --verbose

    - name: Build only async
      run: cargo build --no-default-features --features async --verbose
    
    - name: Run tests only async
      run: cargo test --no-default-features --features async --verbose

    - name: Build rustls
      run: cargo build --no-default-features --features tokio_rustls --verbose
    
    - name: Run tests no async
      run: cargo test --no-default-features --features tokio_rustls --verbose
