name: Rust

on: [push]

jobs:
  build:
    strategy:
    matrix:
      platform: [ubuntu-latest, macos-latest, windows-latest]
      runs-on: ${{ matrix.platform }}    

      steps:
    - uses: actions/checkout@v1

      features: ["", "--no-default-features", "--no-default-features --features async", "--no-default-features --features tokio_rustls" ]
    
    - name: Build default features
      run: cargo ${{ features }} --verbose
    
    - name: Run tests default features
      run: cargo test ${{ features }} --verbose

    - name: Build no features
      run: cargo build ${{ features }} --verbose

    - name: Run tests with no features
      run: cargo test ${{ features }} --verbose

    - name: Build only async
      run: cargo build ${{ features }} --verbose
    
    - name: Run tests only async
      run: cargo test ${{ features }} --verbose

    - name: Build rustls
      run: cargo build ${{ features }} --verbose
    
    - name: Run tests no async
      run: cargo test ${{ features }} --verbose
